# Generated by Django 4.0.6 on 2022-07-16 19:48

import bookkeeping.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Betrag')),
                ('shop', models.CharField(max_length=100, verbose_name='Shop')),
                ('booking_date', models.DateField(verbose_name='Buchungsdatum')),
                ('type', models.CharField(choices=[('IN', 'Einnahme'), ('EX', 'Ausgabe')], max_length=2, verbose_name='Typ')),
                ('comment', models.TextField(verbose_name='Kommentar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eintrag',
                'verbose_name_plural': 'Einträge',
                'ordering': ('booking_date',),
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=bookkeeping.models._user_receipt_path, verbose_name='Belegdatei')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.bookentry')),
            ],
            options={
                'verbose_name': 'Beleg',
                'verbose_name_plural': 'Belege',
            },
        ),
        migrations.AddIndex(
            model_name='bookentry',
            index=models.Index(fields=['booking_date'], name='bookkeeping_booking_543baa_idx'),
        ),
    ]
