# Generated by Django 4.0.6 on 2022-07-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0002_bookentry_receipt_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookentry",
            options={"ordering": ("-booking_date",), "verbose_name": "Eintrag", "verbose_name_plural": "Einträge"},
        ),
    ]
