# Generated by Django 4.0.6 on 2022-08-19 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookkeeping", "0004_tripflatrate_businesstrip"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Benutzer", "verbose_name_plural": "Benutzer"},
        ),
    ]
